version: '3.9'

services:
  www:
    image: php:apache
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
  db:
    image: mysql:latest 
    environment:
      MYSQL_USER: php_docker
      MYSQL_DATABASE: n2r_technologies
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: password
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
      MYSQL_PORT: 3306

